version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: productsdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-app:
    build: .
    container_name: prueba_ada_app
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/productsdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    command: [ "java", "-jar", "app.jar" ]

volumes:
  mysql_data:
